#===============================================================================
# CRIMEGRAPH Configuration file
#===============================================================================

#===============================================================================
# SOURCE
#===============================================================================
source: "FILE"
dataset: "resources/socstream/data/socstream.data"

#===============================================================================
# TOPOLOGY
#===============================================================================
parallelism: 16